# Generated by Django 4.0.5 on 2022-06-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_report_alter_event_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.TextField(default='datum'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(default='text'),
        ),
    ]
