# Generated by Django 4.0.5 on 2022-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_report_date_alter_report_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
