# Generated by Django 4.0.5 on 2022-06-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
